Repository boardStudy/BoardStudy, pull requests merged in 2022-03, with the labels that each got.

#2 Feature/43
  src/main/java/com/hoin/boardStudy/board/config/WebMvcConfigure.java
  src/main/java/com/hoin/boardStudy/board/config/handler/PageRequestHandler.java
  src/main/java/com/hoin/boardStudy/board/controller/BoardController.java
  src/main/java/com/hoin/boardStudy/board/dto/PageInfo.java
Labels: 리팩토링

#23 Feature/10
  src/main/java/com/hoin/boardStudy/user/controller/UserController.java
  src/main/resources/templates/user/signUp.html
Labels: 에러

#24 Feature/16
  src/main/resources/templates/user/signUp.html
Labels: 에러

#30 Refactoring : Login
  src/main/java/com/hoin/boardStudy/user/controller/UserController.java
  src/main/java/com/hoin/boardStudy/user/service/LoginVerification.java
Labels: 리팩토링

#35 SETTING : DB 서버 분리하기
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-real.yml
  src/main/resources/application.yml
Labels: 설정

#34 Feature : 프로필
  src/main/java/com/hoin/boardStudy/user/controller/UserController.java
  src/main/java/com/hoin/boardStudy/user/dto/User.java
  src/main/java/com/hoin/boardStudy/user/mapper/UserMapper.java
  src/main/java/com/hoin/boardStudy/user/service/UserService.java
  src/main/resources/mybatis/mapper/UserMapper.xml
  src/main/resources/templates/common/header.html
  src/main/resources/templates/user/modify.html
  src/main/resources/templates/user/profile.html
  src/main/resources/templates/user/signUp.html
Labels: 기능
