Repository boardStudy/BoardStudy, pull requests merged in 2022-04, with the labels that each got.

#57 ERROR : 페이지네이션 오류
  src/main/resources/templates/board/list.html
Labels: 에러

#56 FEATURE : 파일 첨부
  pom.xml
  src/main/java/com/hoin/boardStudy/board/controller/BoardController.java
  src/main/java/com/hoin/boardStudy/board/dto/FileInfo.java
  src/main/java/com/hoin/boardStudy/board/mapper/BoardMapper.java
  src/main/java/com/hoin/boardStudy/board/mvc/GlobalControllerAdvice.java
  src/main/java/com/hoin/boardStudy/board/service/FileManager.java
  src/main/java/com/hoin/boardStudy/user/service/PasswordManagement.java
  src/main/java/com/hoin/boardStudy/util/FileConfig.java
  src/main/resources/application.yml
  src/main/resources/mybatis-config.xml
  src/main/resources/mybatis/mapper/BoardMapper.xml
  src/main/resources/templates/board/detail.html
  src/main/resources/templates/board/modify.html
  src/main/resources/templates/board/writeForm.html
  src/test/java/com/hoin/boardStudy/BoardApplicationTests.java
  src/test/java/com/hoin/boardStudy/JustTest.java
Labels: 기능

#60 [ERROR] 페이지네이션 세로로 출력되는 에러
  src/main/resources/templates/board/list.html
Labels: 에러

#62 파일 업로드 경로 반영
  Dockerfile
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-real.yml
  src/main/resources/application.yml
Labels: 설정

#67 FEATURE : 로그인 체크 인터셉터 사용
  src/main/java/com/hoin/boardStudy/board/config/WebMvcConfigure.java
  src/main/java/com/hoin/boardStudy/board/config/filter/LoginCheck.java
  src/main/java/com/hoin/boardStudy/board/controller/BoardController.java
Labels: 기능

#68 FEATURE : 프로필
  src/main/java/com/hoin/boardStudy/user/controller/UserController.java
  src/main/resources/templates/user/profile.html
Labels: 기능

#71 Fix : 필터 적용 후 에러 발생
  src/main/java/com/hoin/boardStudy/board/config/filter/LoginCheck.java
Labels: 에러

#66 [FEATURE] 새로운 글에 NEW 달아주기
  src/main/java/com/hoin/boardStudy/board/controller/BoardController.java
  src/main/java/com/hoin/boardStudy/board/dto/Board.java
  src/main/java/com/hoin/boardStudy/board/service/BoardService.java
  src/main/java/com/hoin/boardStudy/board/service/NewArticleChecker.java
  src/main/resources/static/images/new.png
  src/main/resources/templates/board/list.html
Labels: 기능

#72 FEATURE : 페이지네이션 선택
  src/main/resources/templates/board/list.html
Labels: 기능

#74 Error : image 파일 안 뜨는 오류
  src/main/java/com/hoin/boardStudy/board/config/filter/LoginCheck.java
Labels: 에러

#77 Feature : 다중 파일 업로드 / 다운로드로 변경
  src/main/java/com/hoin/boardStudy/board/config/filter/LoginCheck.java
  src/main/java/com/hoin/boardStudy/board/controller/BoardController.java
  src/main/java/com/hoin/boardStudy/board/mapper/BoardMapper.java
  src/main/java/com/hoin/boardStudy/board/service/FileManager.java
  src/main/resources/mybatis/mapper/BoardMapper.xml
  src/main/resources/templates/board/detail.html
  src/main/resources/templates/board/modify.html
  src/main/resources/templates/board/writeForm.html
Labels: 기능

#82 index 페이지 작성
  src/main/resources/templates/common/header.html
  src/main/resources/templates/index.html
Labels: 설정

#83 feature : session관리 redis 설정
  pom.xml
  src/main/java/com/hoin/boardStudy/BoardApplication.java
  src/main/java/com/hoin/boardStudy/board/config/RedisConfigure.java
  src/main/java/com/hoin/boardStudy/board/dto/BoardSaveRequest.java
  src/main/java/com/hoin/boardStudy/user/dto/User.java
  src/main/java/com/hoin/boardStudy/util/RedisConfig.java
  src/main/resources/application.yml
Labels: 기능

#91 favicon
  src/main/resources/static/images/favicon.ico
  src/main/resources/templates/board/detail.html
  src/main/resources/templates/board/list.html
  src/main/resources/templates/board/modify.html
  src/main/resources/templates/board/writeForm.html
  src/main/resources/templates/common/header.html
  src/main/resources/templates/index.html
Labels: 리팩토링, 기능
